/*
NRF NFManagement Service

Testing SubscriptionIDDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_SubscriptionIDDocumentAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SubscriptionIDDocumentAPIService RemoveSubscription", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subscriptionID string

		httpRes, err := apiClient.SubscriptionIDDocumentAPI.RemoveSubscription(context.Background(), subscriptionID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscriptionIDDocumentAPIService UpdateSubscription", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subscriptionID string

		resp, httpRes, err := apiClient.SubscriptionIDDocumentAPI.UpdateSubscription(context.Background(), subscriptionID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
