/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AmfCond type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AmfCond{}

// AmfCond Subscription to a set of AMFs, based on AMF Set Id and/or AMF Region Id
type AmfCond struct {
	// String identifying the AMF Set ID (10 bits) as specified in clause 2.10.1 of 3GPP TS 23.003.  It is encoded as a string of 3 hexadecimal characters where the first character is limited to  values 0 to 3 (i.e. 10 bits). 
	AmfSetId *string `json:"amfSetId,omitempty"`
	// String identifying the AMF Set ID (10 bits) as specified in clause 2.10.1 of 3GPP TS 23.003.  It is encoded as a string of 3 hexadecimal characters where the first character is limited to  values 0 to 3 (i.e. 10 bits) 
	AmfRegionId *string `json:"amfRegionId,omitempty"`
}

// NewAmfCond instantiates a new AmfCond object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmfCond() *AmfCond {
	this := AmfCond{}
	return &this
}

// NewAmfCondWithDefaults instantiates a new AmfCond object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmfCondWithDefaults() *AmfCond {
	this := AmfCond{}
	return &this
}

// GetAmfSetId returns the AmfSetId field value if set, zero value otherwise.
func (o *AmfCond) GetAmfSetId() string {
	if o == nil || IsNil(o.AmfSetId) {
		var ret string
		return ret
	}
	return *o.AmfSetId
}

// GetAmfSetIdOk returns a tuple with the AmfSetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmfCond) GetAmfSetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AmfSetId) {
		return nil, false
	}
	return o.AmfSetId, true
}

// HasAmfSetId returns a boolean if a field has been set.
func (o *AmfCond) HasAmfSetId() bool {
	if o != nil && !IsNil(o.AmfSetId) {
		return true
	}

	return false
}

// SetAmfSetId gets a reference to the given string and assigns it to the AmfSetId field.
func (o *AmfCond) SetAmfSetId(v string) {
	o.AmfSetId = &v
}

// GetAmfRegionId returns the AmfRegionId field value if set, zero value otherwise.
func (o *AmfCond) GetAmfRegionId() string {
	if o == nil || IsNil(o.AmfRegionId) {
		var ret string
		return ret
	}
	return *o.AmfRegionId
}

// GetAmfRegionIdOk returns a tuple with the AmfRegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmfCond) GetAmfRegionIdOk() (*string, bool) {
	if o == nil || IsNil(o.AmfRegionId) {
		return nil, false
	}
	return o.AmfRegionId, true
}

// HasAmfRegionId returns a boolean if a field has been set.
func (o *AmfCond) HasAmfRegionId() bool {
	if o != nil && !IsNil(o.AmfRegionId) {
		return true
	}

	return false
}

// SetAmfRegionId gets a reference to the given string and assigns it to the AmfRegionId field.
func (o *AmfCond) SetAmfRegionId(v string) {
	o.AmfRegionId = &v
}

func (o AmfCond) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AmfCond) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AmfSetId) {
		toSerialize["amfSetId"] = o.AmfSetId
	}
	if !IsNil(o.AmfRegionId) {
		toSerialize["amfRegionId"] = o.AmfRegionId
	}
	return toSerialize, nil
}

type NullableAmfCond struct {
	value *AmfCond
	isSet bool
}

func (v NullableAmfCond) Get() *AmfCond {
	return v.value
}

func (v *NullableAmfCond) Set(val *AmfCond) {
	v.value = val
	v.isSet = true
}

func (v NullableAmfCond) IsSet() bool {
	return v.isSet
}

func (v *NullableAmfCond) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmfCond(val *AmfCond) *NullableAmfCond {
	return &NullableAmfCond{value: val, isSet: true}
}

func (v NullableAmfCond) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmfCond) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


