/*
NRF NFManagement Service

NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.1.0.alpha-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetNFInstances200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNFInstances200Response{}

// GetNFInstances200Response struct for GetNFInstances200Response
type GetNFInstances200Response struct {
	// List of the URI of NF instances. It has two members whose names are item and self. The item one contains an array of URIs.
	Links *map[string]LinksValueSchema `json:"_links,omitempty"`
}

// NewGetNFInstances200Response instantiates a new GetNFInstances200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNFInstances200Response() *GetNFInstances200Response {
	this := GetNFInstances200Response{}
	return &this
}

// NewGetNFInstances200ResponseWithDefaults instantiates a new GetNFInstances200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNFInstances200ResponseWithDefaults() *GetNFInstances200Response {
	this := GetNFInstances200Response{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetNFInstances200Response) GetLinks() map[string]LinksValueSchema {
	if o == nil || IsNil(o.Links) {
		var ret map[string]LinksValueSchema
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNFInstances200Response) GetLinksOk() (*map[string]LinksValueSchema, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetNFInstances200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]LinksValueSchema and assigns it to the Links field.
func (o *GetNFInstances200Response) SetLinks(v map[string]LinksValueSchema) {
	o.Links = &v
}

func (o GetNFInstances200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNFInstances200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableGetNFInstances200Response struct {
	value *GetNFInstances200Response
	isSet bool
}

func (v NullableGetNFInstances200Response) Get() *GetNFInstances200Response {
	return v.value
}

func (v *NullableGetNFInstances200Response) Set(val *GetNFInstances200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNFInstances200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNFInstances200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNFInstances200Response(val *GetNFInstances200Response) *NullableGetNFInstances200Response {
	return &NullableGetNFInstances200Response{value: val, isSet: true}
}

func (v NullableGetNFInstances200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNFInstances200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


